"""
Contiene los programas pre-cargados (en ROM) del simulador.
"""

CALCULATOR_PROGRAM = [
    "# Calculadora de Suma Simple Interactiva",
    "# Pide dos números y muestra el resultado.",
    "",
    "# --- Mensaje de Bienvenida ---",
    "LOADI 'B'", "OUT",
    "LOADI 'I'", "OUT",
    "LOADI 'E'", "OUT",
    "LOADI 'N'", "OUT",
    "LOADI 'V'", "OUT",
    "LOADI 'E'", "OUT",
    "LOADI 'N'", "OUT",
    "LOADI 'I'", "OUT",
    "LOADI 'D'", "OUT",
    "LOADI 'O'", "OUT",
    "LOADI 'S'", "OUT",
    "LOADI 10", "OUT",
    "LOADI 'C'", "OUT",
    "LOADI 'A'", "OUT",
    "LOADI 'L'", "OUT",
    "LOADI 'C'", "OUT",
    "LOADI 'U'", "OUT",
    "LOADI 'L'", "OUT",
    "LOADI 'A'", "OUT",
    "LOADI 'D'", "OUT",
    "LOADI 'O'", "OUT",
    "LOADI 'R'", "OUT",
    "LOADI 'A'", "OUT",
    "LOADI ' '", "OUT",
    "LOADI 'S'", "OUT",
    "LOADI 'I'", "OUT",
    "LOADI 'M'", "OUT",
    "LOADI 'P'", "OUT",
    "LOADI 'L'", "OUT",
    "LOADI 'E'", "OUT",
    "LOADI 10", "OUT",
    "LOADI 10", "OUT",
    "",
    "# --- Lógica del Programa ---",
    "# 1. Pedir el primer número",
    "LOADI 'I'", "OUT",
    "LOADI 'n'", "OUT",
    "LOADI 'g'", "OUT",
    "LOADI 'r'", "OUT",
    "LOADI 'e'", "OUT",
    "LOADI 's'", "OUT",
    "LOADI 'e'", "OUT",
    "LOADI ' '", "OUT",
    "LOADI 'e'", "OUT",
    "LOADI 'l'", "OUT",
    "LOADI ' '", "OUT",
    "LOADI 'p'", "OUT",
    "LOADI 'r'", "OUT",
    "LOADI 'i'", "OUT",
    "LOADI 'm'", "OUT",
    "LOADI 'e'", "OUT",
    "LOADI 'r'", "OUT",
    "LOADI ' '", "OUT",
    "LOADI 'n'", "OUT",
    "LOADI 'u'", "OUT",
    "LOADI 'm'", "OUT",
    "LOADI 'e'", "OUT",
    "LOADI 'r'", "OUT",
    "LOADI 'o'", "OUT",
    "LOADI ':'", "OUT",
    "LOADI ' '", "OUT",
    "",
    "# 2. Leer el primer número",
    "IN         # Espera un Enter, AC = número ingresado",
    "STORE 250  # Guarda en Mem[250]",
    "",
    "# 3. Pedir el segundo número",
    "LOADI 10", "OUT",
    "LOADI 'I'", "OUT",
    "LOADI 'n'", "OUT",
    "LOADI 'g'", "OUT",
    "LOADI 'r'", "OUT",
    "LOADI 'e'", "OUT",
    "LOADI 's'", "OUT",
    "LOADI 'e'", "OUT",
    "LOADI ' '", "OUT",
    "LOADI 'e'", "OUT",
    "LOADI 'l'", "OUT",
    "LOADI ' '", "OUT",
    "LOADI 's'", "OUT",
    "LOADI 'e'", "OUT",
    "LOADI 'g'", "OUT",
    "LOADI 'u'", "OUT",
    "LOADI 'n'", "OUT",
    "LOADI 'd'", "OUT",
    "LOADI 'o'", "OUT",
    "LOADI ' '", "OUT",
    "LOADI 'n'", "OUT",
    "LOADI 'u'", "OUT",
    "LOADI 'm'", "OUT",
    "LOADI 'e'", "OUT",
    "LOADI 'r'", "OUT",
    "LOADI 'o'", "OUT",
    "LOADI ':'", "OUT",
    "LOADI ' '", "OUT",
    "",
    "# 4. Leer el segundo número",
    "IN         # Espera un Enter, AC = número ingresado",
    "",
    "# 5. Sumar y guardar el resultado",
    "ADD 250    # AC = suma de los dos números",
    "STORE 252  # Guarda la suma en Mem[252]",
    "",
    "# 6. Mostrar mensaje de resultado",
    "LOADI 10", "OUT",
    "LOADI 'E'", "OUT",
    "LOADI 'l'", "OUT",
    "LOADI ' '", "OUT",
    "LOADI 'r'", "OUT",
    "LOADI 'e'", "OUT",
    "LOADI 's'", "OUT",
    "LOADI 'u'", "OUT",
    "LOADI 'l'", "OUT",
    "LOADI 't'", "OUT",
    "LOADI 'a'", "OUT",
    "LOADI 'd'", "OUT",
    "LOADI 'o'", "OUT",
    "LOADI ' '", "OUT",
    "LOADI 'e'", "OUT",
    "LOADI 's'", "OUT",
    "LOADI ':'", "OUT",
    "LOADI ' '", "OUT",
    "",
    "# 7. Recuperar la suma",
    "LOAD 252   # Carga la suma de nuevo en AC",
    "",
    "# 8. Imprimir el resultado numérico",
    "OUTNUM",
    "",
    "# 9. Fin del programa",
    "HALT",
]
